import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/navbar/navbar";
import Footer from "@/components/global/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"bg-white text-black dark:bg-black dark:text-white"}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
